/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three';
import React from 'react';
import { Center, useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    Text: THREE.Mesh;
  };
};

export default function AboutMeText(props: JSX.IntrinsicElements['group']) {
  const { nodes } = useGLTF('/models/aboutMe.glb') as GLTFResult;
  return (
    <Center position={[0, 33, -10]} rotation-x={Math.PI * 0.5} scale={10}>
      <group {...props} dispose={null}>
        <mesh geometry={nodes.Text.geometry}>
          <meshBasicMaterial color="#ffffff" />
        </mesh>
      </group>
    </Center>
  );
}

useGLTF.preload('/aboutMe.glb');
