/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three';
import React from 'react';
import { useGLTF, useTexture } from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import Floor from './Floor';

type GLTFResult = GLTF & {
  nodes: {
    windows: THREE.Mesh;
    waters: THREE.Mesh;
    buildings: THREE.Mesh;
  };
  materials: {};
};

export default function Buildings() {
  const { nodes } = useGLTF('/buildings.glb') as GLTFResult;
  const bakedTexture = useTexture('/bakedTexture.jpg');
  const waterTexture = useTexture('/bakedWater.png');
  const windowTexture = useTexture('/matcap.jpg');
  bakedTexture.flipY = false;
  waterTexture.flipY = false;

  // useFrame((state) => {
  //   console.log(state.camera.position);
  //   console.log(state.camera.rotation);
  // });

  return (
    <group dispose={null}>
      <mesh geometry={nodes.windows.geometry}>
        <meshMatcapMaterial matcap={windowTexture} />
      </mesh>
      <mesh geometry={nodes.waters.geometry}>
        <meshBasicMaterial map={waterTexture} transparent />
      </mesh>
      <mesh geometry={nodes.buildings.geometry}>
        <meshBasicMaterial map={bakedTexture} />
      </mesh>
      <Floor />
    </group>
  );
}

useGLTF.preload('/buildings.glb');
